name: Test package

on: [push]


jobs:
  test-code:
    runs-on: ubuntu-22.04
    container: ghcr.io/fenics/dolfinx/dolfinx:nightly
    env:
      DEB_PYTHON_INSTALL_LAYOUT: deb_system


    steps:
      - uses: actions/checkout@v3

      - name: Install package
        run: python3 -m pip install .[test]

      - name: Run tests
        run: python3 -m pytest -v

      - name: Coverage report
        if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v3
